### ISSUE TITLE
[Bug]  Missing Features

### ISSUE THREAD

**Issue by sileeb** [Cookie-AutoDelete/Cookie-AutoDelete#1384] opened 2022-05-08 17:38 UTC
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Describe the bug

Hi kenneth.. I noticed an option thats missing. In the icon popup window under 'options', the features to check/uncheck different elements like cache, service workers, etc are no longer there. Is this feature missing?

### To Reproduce

Go to icon popup window

### Expected Behavior

Its supposed to have features like cache, service workers, etc

### System Info - Operating System (OS)

win 10

### System Info - Browser Info

ff 100

### System Info - CookieAutoDelete Version

360

**Comment by kennethtran93** [comment] 2022-05-08 23:54
Duplicate of #1329, fixed in #1363 (you can temporarily use the one posted in the PR for now if you want. 

Version bump soon.

**Closed** 2022-05-08 23:56 UTC
Labels: duplicate, Firefox

**Comment by sileeb** [comment] 2022-05-09 00:21
Hi kenneth.. so wheres the temp fix? I dont see it. And when will you release the official fixed version?

**Comment by kennethtran93** [comment] 2022-05-09 00:25
It is in a comment inside the PR.

https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/pull/1363#issuecomment-1095424279

**Comment by sileeb** [comment] 2022-05-09 00:37
Very sorry for my ignorance, but whats or where is PR?

**Comment by kennethtran93** [comment] 2022-05-09 04:08
PR stands for 'Pull Request'. There is a direct link in my last post that will take you to the comment in that pull request that contains a zip attachment for FireFox that contains the fix for FireFox 100+.
