### ISSUE TITLE
Feature request - list cookies for domain

### ISSUE THREAD

**Issue by webac** [Cookie-AutoDelete/Cookie-AutoDelete#110] opened 2017-08-19 12:58 UTC
Thanks for this great WebExtention !

It will be helpfull if you can add a link/icon to list the cookies for the current domain or just a link to the native Firefox window.

![image](https://user-images.githubusercontent.com/2668750/29486801-c4f46cb4-84ee-11e7-80a4-d5047ae24fc7.png)

Thank You

**Comment by mrdokenny** [comment] 2017-08-21 19:12
No idea if WebExtensions will allow a shortcut link to that, so we'll see...

**Comment by webac** [comment] 2017-08-24 11:47
The only url I found is to display all cookies : chrome://browser/content/preferences/cookies.xul (not helpfull),

Maybe, using the WebExtentions API, you can list cookies for the current domain on the popup.html by clicking a link, 
and then you can add a link to go back.

https://github.com/mdn/webextensions-examples/tree/master/list-cookies

**Comment by tomhughes** [comment] 2017-10-17 12:00
You can pass a `filterString` argument when opening the dialog, like this:

```
window.openDialog("chrome://browser/content/preferences/cookies.xul", "", "", { filterString: "example.com" })
```

**Comment by ghost** [comment] 2017-10-27 13:48
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/87

**Comment by ke-d** [comment] 2017-12-28 21:24
Duplicate of #87

**Closed by ke-d** 2017-12-28 21:24 UTC
