### ISSUE TITLE
Hard to read on Linux dark system theme

### ISSUE THREAD

**Issue by Nindaleth** [Cookie-AutoDelete/Cookie-AutoDelete#31] opened 2017-05-26 08:52 UTC
I'm running Firefox 53 on Linux (Ubuntu 16.04.2 LTS) with a dark system theme (Arc-Dark). It seems that while dialog background color is taken from system, the text color is hardcoded to black and thus the result isn't exactly readable:

![cookie_autodelete_dark](https://cloud.githubusercontent.com/assets/6383928/26487404/acfb208a-41ff-11e7-8e3e-59d05be06a05.png)

**Comment by mrdokenny** [comment] 2017-05-27 03:04
Do any other WebExtension have this problem?

**Comment by Nindaleth** [comment] 2017-06-01 08:09
Privacy Settings has black-on-grey buttons on the bottom bar, but I'm not sure whether it's a WebExtension.

**Comment by mrdokenny** [comment] 2017-06-05 03:04
It has access to about:config, so not a WebExtension. 

I've been looking into it and it seems I might want to add browser_style: true in the manifest.json.

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/browser_action#Syntax

**Comment by mrdokenny** [comment] 2017-07-14 14:53
@Nindaleth So 1.4.1 came out and I added 6f0b3d582f012cb893ce3cd8a0429920bd934404. Let me know if it fixes that problem for you.

**Comment by Nindaleth** [comment] 2017-07-17 11:25
I tried it out, but it still looks the same.

I found a workaround in a relevant Firefox bug, but that workaround didn't help:
https://bugzilla.mozilla.org/show_bug.cgi?id=70315#c31

Further relevant bugs:
https://bugzilla.mozilla.org/show_bug.cgi?id=1283086
https://bugzilla.mozilla.org/show_bug.cgi?id=1158076

This suggests to me that the used theme is correct, your code is correct, and the bug is in Firefox itself.

**Comment by hackel** [comment] 2017-08-11 16:25
Just came here to report this very issue.  This is with a freshly installed copy of 1.4.1 on FF54.

![image](https://user-images.githubusercontent.com/583677/29222331-a0789166-7e87-11e7-80d3-8477c7392a06.png)

Isn't it simply a matter of specifying a background-color in CSS?

**Comment by hackel** [comment] 2017-08-11 17:13
I looked into this a little bit and the problem is two-fold.  First, you're using this `skeleton.css` file which overrides the browser's default colours.  That's no good.  Second, Firefox has an extension.css file that is *also* for some reason overriding colors from the parent.

So, what we want is for the color to be set to the CSS variable `--lwt-text-color`.  If you add this as a manual style, it fixes everything.  What we see instead, is that:
extensions.css sets `color: #222426` on the html,body tags.
Then, skeleton.css:123 sets `color: #222` on the body tag.

I guess this is because the browser treats the extension drop-down menu as a separate HTML document, resetting color to #000, while the background-color is still getting set by the theme.  Even setting `color: inherit` doesn't allow the browser chrome style to come through.  

So, I don't know if this can be fixed in this extension (perhaps some javascript could detect whether the background is dark or not, but that doesn't seem ideal), but more likely needs to be fixed in Firefox itself.  I do not experience this issue in Chromium, where the drop-down appears with a white background.  In the meantime, a work-around is to just set the background to white in userChrome.css:
```css
[viewId="PanelUI-webext-cookieautodelete_kennydo_com-browser-action-view"] .panel-arrowcontent {
  background: white !important;
}
```

**Comment by mrdokenny** [comment] 2017-08-11 17:39
@hackel What about other WebExtensions popups?

**Comment by NoXPhasma** [comment] 2017-09-17 15:34
I have the same problem. To your question @mrdokenny, other WebExtension popups have the same issue, if they aren't styled. To name two: [Stylus](https://addons.mozilla.org/en-US/firefox/addon/styl-us/) and [Violentmonkey](https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/)

**Comment by ke-d** [comment] 2018-05-09 05:18
Closing for inactivity and since many things has changed in the UI in general, it doesn't make sense for this to be open anymore.

**Closed by ke-d** 2018-05-09 05:18 UTC
Labels: browserbug/limitation
